# Generated by Django 4.0.4 on 2023-03-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('birth_date', models.DateField(default='2003-09-08')),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('address', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField(null=True)),
                ('email_id', models.CharField(max_length=255)),
                ('add_image', models.ImageField(upload_to='./face_images/')),
            ],
        ),
    ]
