# Generated by Django 4.0.4 on 2023-03-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondata',
            name='password',
            field=models.CharField(default='1234', max_length=20),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persondata',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
